### ISSUE TITLE
Readonly UI

### ISSUE THREAD

**Issue by timja** [idobry/flux-web#5]
It would be good to be able tonot allow promotion through the UI, just have it for viewing the versions deployed / available

**Comment by idobry** [comment]
Are you suggesting we should implement users authorizations?
This is something I do think about.

**Comment by timja** [comment]
Not sure if users is needed for this, it could be a command line flag or env variable

**Comment by idobry** [comment]
#7

**Comment by idobry** [comment]
#7 I'm closing this if you guys see any issue please reopen
